#!/usr/bin/bash

read -p "choose-deployment: " deployment
read -p "replicas_count: " replicas_count
read -p "k8s-resource-type: " type

# k8s scale up

kubectl scale --replicas=$replicas_count $type/$deployment

# show progress bar

echo -ne '###                    (10%)\r'
sleep 1
echo -ne '#####                  (25%)\r'
sleep 1
echo -ne '########               (50%)\r'
sleep 1
echo -ne '#############          (60%)\r'
sleep 1
echo -ne '##################     (75%)\r'
sleep 1
echo -ne '######################(100%)\r'
echo -ne '\n'

# k8s scale up completed

echo "$type $deployment scale up to $replicas_count"
